services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    command: --no-analytics
    restart: always
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9000:9000"
    environment:
      - TZ=Europe/Istanbul
    networks:
      - portainer_network

networks:
  portainer_network:
    name: portainer_network
    driver: bridge

volumes:
  portainer_data:
    name: portainer_data
