services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - uptime_kuma_data:/app/data
    ports:
      - 3001:3001
    restart: always

volumes:
  uptime_kuma_data:
    name: uptime_kuma_data
